name: Terraform Apply

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "0.14.4"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip -o terraform_"$tf_version"_linux_amd64.zip
        sudo mv -f terraform /usr/local/bin/

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      working-directory: ./terraform/tf_event_bus
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_S3_KEY: ${{ secrets.AWS_S3_KEY }}
      run: |
        export TF_CLI_ARGS_init="-backend-config='access_key=$AWS_ACCESS_KEY_ID' -backend-config='secret_key=$AWS_SECRET_ACCESS_KEY' -backend-config='token=$AWS_SESSION_TOKEN' -backend-config='role_arn=$AWS_ROLE_ARN' -backend-config='bucket=$AWS_S3_BUCKET' -backend-config='key=$AWS_S3_KEY'"
        terraform init -input=false

    - name: Terraform create workspace
      working-directory: ./terraform/tf_event_bus
      run: terraform workspace select ${GITHUB_REF##*/}

    - name: Terraform validation
      working-directory: ./terraform/tf_event_bus
      run: terraform validate

    - name: Terraform apply
      working-directory: ./terraform/tf_event_bus
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        AWS_REGION: eu-west-1
      run: |
        export TF_CLI_ARGS_apply="-var='AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' -var='AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' -var='AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN' -var='AWS_ROLE_ARN=$AWS_ROLE_ARN' -var='AWS_REGION=$AWS_REGION'"
        terraform apply -auto-approve -input=false

